// Common countries list - sorted alphabetically by label
export const COUNTRIES = [
  { value: "AR", label: "Argentina", labelZh: "阿根廷" },
  { value: "AU", label: "Australia", labelZh: "澳大利亚" },
  { value: "AT", label: "Austria", labelZh: "奥地利" },
  { value: "BD", label: "Bangladesh", labelZh: "孟加拉国" },
  { value: "BE", label: "Belgium", labelZh: "比利时" },
  { value: "BR", label: "Brazil", labelZh: "巴西" },
  { value: "CA", label: "Canada", labelZh: "加拿大" },
  { value: "CL", label: "Chile", labelZh: "智利" },
  { value: "CN", label: "China", labelZh: "中国" },
  { value: "CO", label: "Colombia", labelZh: "哥伦比亚" },
  { value: "EG", label: "Egypt", labelZh: "埃及" },
  { value: "FR", label: "France", labelZh: "法国" },
  { value: "DE", label: "Germany", labelZh: "德国" },
  { value: "HK", label: "Hong Kong", labelZh: "香港" },
  { value: "ID", label: "Indonesia", labelZh: "印度尼西亚" },
  { value: "IN", label: "India", labelZh: "印度" },
  { value: "IE", label: "Ireland", labelZh: "爱尔兰" },
  { value: "IT", label: "Italy", labelZh: "意大利" },
  { value: "JP", label: "Japan", labelZh: "日本" },
  { value: "KR", label: "South Korea", labelZh: "韩国" },
  { value: "MY", label: "Malaysia", labelZh: "马来西亚" },
  { value: "MX", label: "Mexico", labelZh: "墨西哥" },
  { value: "NL", label: "Netherlands", labelZh: "荷兰" },
  { value: "NZ", label: "New Zealand", labelZh: "新西兰" },
  { value: "NG", label: "Nigeria", labelZh: "尼日利亚" },
  { value: "PE", label: "Peru", labelZh: "秘鲁" },
  { value: "PH", label: "Philippines", labelZh: "菲律宾" },
  { value: "PK", label: "Pakistan", labelZh: "巴基斯坦" },
  { value: "PL", label: "Poland", labelZh: "波兰" },
  { value: "RU", label: "Russia", labelZh: "俄罗斯" },
  { value: "SA", label: "Saudi Arabia", labelZh: "沙特阿拉伯" },
  { value: "SG", label: "Singapore", labelZh: "新加坡" },
  { value: "ES", label: "Spain", labelZh: "西班牙" },
  { value: "SE", label: "Sweden", labelZh: "瑞典" },
  { value: "CH", label: "Switzerland", labelZh: "瑞士" },
  { value: "TW", label: "Taiwan", labelZh: "台湾" },
  { value: "TH", label: "Thailand", labelZh: "泰国" },
  { value: "TR", label: "Turkey", labelZh: "土耳其" },
  { value: "AE", label: "UAE", labelZh: "阿联酋" },
  { value: "GB", label: "United Kingdom", labelZh: "英国" },
  { value: "US", label: "United States", labelZh: "美国" },
  { value: "ZA", label: "South Africa", labelZh: "南非" },
  { value: "VN", label: "Vietnam", labelZh: "越南" },
] as const;

export type CountryCode = typeof COUNTRIES[number]['value'];